# Generated by Django 5.2.6 on 2026-06-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Aboboyaa Tricycle', 'Aboboyaa Tricycle'), ('KIA Bongo 1.5 Ton', 'KIA Bongo 1.5 Ton'), ('Cargo Truck', 'Cargo Truck')], default='Aboboyaa Tricycle', max_length=30)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_MATCH', 'Pending Transporter Match'), ('MATCHED', 'Transporter Matched'), ('PICKED_UP', 'Picked Up / In Transit'), ('DELIVERED', 'Delivered')], default='PENDING_MATCH', max_length=25)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
