# Generated by Django 5.2.6 on 2026-06-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportjob',
            name='status',
            field=models.CharField(choices=[('PENDING_MATCH', 'Pending Transporter Match'), ('PENDING_APPROVAL', 'Pending Buyer Approval'), ('MATCHED', 'Transporter Matched'), ('PICKED_UP', 'Picked Up / In Transit'), ('DELIVERED', 'Delivered')], default='PENDING_MATCH', max_length=25),
        ),
    ]
