# Generated by Django 5.2.6 on 2026-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_transportjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportjob',
            name='paid_by',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer'), ('UNSET', 'Unset')], default='UNSET', max_length=10),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('PAID', 'Paid')], default='PENDING', max_length=15),
        ),
    ]
