# Generated by Django 6.0.6 on 2026-08-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_transportjob_paid_by_transportjob_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportjob',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='negotiation_status',
            field=models.CharField(choices=[('NONE', 'No Negotiation'), ('PENDING_BUYER_APPROVAL', 'Pending Buyer Price Approval'), ('PENDING_DRIVER_APPROVAL', 'Pending Driver Counter-Offer Approval')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
