# Generated by Django 5.2.6 on 2026-06-17 19:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tomatoes', 'Tomatoes'), ('Habanero Peppers', 'Habanero Peppers'), ('Garden Eggs', 'Garden Eggs'), ('Okra', 'Okra'), ('Leafy Greens', 'Leafy Greens')], max_length=50)),
                ('variety', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('Crates', 'Crates'), ('Sacks', 'Sacks'), ('Baskets', 'Baskets'), ('Boxes', 'Boxes')], default='Crates', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_date', models.DateField()),
                ('posting_date', models.DateField(default=datetime.date.today)),
                ('predicted_rot_date', models.DateField(blank=True, null=True)),
                ('freshness_score', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
