# Generated by Django 5.2.6 on 2026-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0003_storagefacility_produce_storage_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='demand_level',
            field=models.CharField(choices=[('HIGH', 'High Demand'), ('MEDIUM', 'Medium Demand'), ('LOW', 'Low Demand')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='produce',
            name='discount_recommendation_status',
            field=models.CharField(choices=[('NONE', 'No Recommendation Needed'), ('PENDING_FARMER_DECISION', 'Pending Farmer Decision'), ('ACCEPTED', 'Accepted by Farmer'), ('REJECTED', 'Rejected by Farmer')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='produce',
            name='original_listing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='recommended_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
