from django.utils import timezone
from django.db import connection
from rest_framework import status, permissions
from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Produce, StorageFacility
from .serializers import ProduceSerializer, StorageFacilitySerializer


def _ensure_storage_table_schema():
    """Auto-create produce_storagefacility table and storage_facility_id column if missing"""
    try:
        with connection.cursor() as cursor:
            # Check if vendor is postgresql
            is_postgres = connection.vendor == 'postgresql'
            
            if is_postgres:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS produce_storagefacility (
                        id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(150) NOT NULL,
                        facility_type varchar(50) NOT NULL,
                        capacity varchar(100) NOT NULL,
                        location varchar(200) NOT NULL,
                        temperature_humidity varchar(100) NOT NULL,
                        photo_url varchar(255) NOT NULL,
                        status varchar(30) NOT NULL,
                        badge varchar(30) NOT NULL,
                        admin_notes text NOT NULL,
                        inspected_at timestamp with time zone NULL,
                        created_at timestamp with time zone NOT NULL,
                        updated_at timestamp with time zone NOT NULL,
                        farmer_id bigint NOT NULL,
                        inspected_by_id bigint NULL
                    );
                """)
            else:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS produce_storagefacility (
                        id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                        name varchar(150) NOT NULL,
                        facility_type varchar(50) NOT NULL,
                        capacity varchar(100) NOT NULL,
                        location varchar(200) NOT NULL,
                        temperature_humidity varchar(100) NOT NULL,
                        photo_url varchar(255) NOT NULL,
                        status varchar(30) NOT NULL,
                        badge varchar(30) NOT NULL,
                        admin_notes text NOT NULL,
                        inspected_at datetime NULL,
                        created_at datetime NOT NULL,
                        updated_at datetime NOT NULL,
                        farmer_id integer NOT NULL,
                        inspected_by_id integer NULL
                    );
                """)

            cursor.execute("""
                SELECT column_name FROM information_schema.columns 
                WHERE table_name = 'produce_produce' AND column_name = 'storage_facility_id';
            """)
            if not cursor.fetchone():
                cursor.execute("ALTER TABLE produce_produce ADD COLUMN storage_facility_id bigint NULL;")

            # Auto-remediate any legacy columns on produce_produce with NOT NULL constraints (e.g. freshness_status)
            if is_postgres:
                cursor.execute("""
                    SELECT column_name, data_type 
                    FROM information_schema.columns 
                    WHERE table_name = 'produce_produce' 
                      AND is_nullable = 'NO' 
                      AND column_name NOT IN ('id', 'name', 'quantity_available', 'unit', 'price_per_unit', 'harvest_date', 'posting_date', 'freshness_score', 'farmer_id');
                """)
                legacy_cols = cursor.fetchall()
                for col_name, data_type in legacy_cols:
                    try:
                        cursor.execute(f'ALTER TABLE produce_produce ALTER COLUMN "{col_name}" DROP NOT NULL;')
                        if 'char' in data_type or 'text' in data_type:
                            cursor.execute(f'ALTER TABLE produce_produce ALTER COLUMN "{col_name}" SET DEFAULT \'\';')
                        elif 'int' in data_type or 'decimal' in data_type or 'numeric' in data_type or 'float' in data_type:
                            cursor.execute(f'ALTER TABLE produce_produce ALTER COLUMN "{col_name}" SET DEFAULT 0;')
                    except Exception as col_err:
                        print(f"Column fix note for {col_name}:", col_err)
    except Exception as e:
        print("Storage schema check note:", e)

_ensure_storage_table_schema()




class StorageFacilityListCreateView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request):
        farmer_id = request.query_params.get('farmer')
        if farmer_id:
            facilities = StorageFacility.objects.filter(farmer_id=farmer_id).order_by('-id')
        else:
            # Show all facilities or only approved ones if public
            if request.user.is_authenticated and request.user.role == 'FARMER':
                facilities = StorageFacility.objects.filter(farmer=request.user).order_by('-id')
            else:
                facilities = StorageFacility.objects.filter(status='APPROVED').order_by('-id')
                
        serializer = StorageFacilitySerializer(facilities, many=True)
        return Response(serializer.data)

    def post(self, request):
        if not request.user.is_authenticated:
            return Response({'detail': 'Authentication required'}, status=status.HTTP_401_UNAUTHORIZED)
            
        serializer = StorageFacilitySerializer(data=request.data)
        if serializer.is_valid():
            facility = serializer.save(farmer=request.user)
            return Response(StorageFacilitySerializer(facility).data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class StorageFacilityInspectView(APIView):
    permission_classes = [permissions.IsAdminUser]

    def post(self, request, pk):
        try:
            facility = StorageFacility.objects.get(pk=pk)
        except StorageFacility.DoesNotExist:
            return Response({'detail': 'Storage facility not found'}, status=status.HTTP_404_NOT_FOUND)

        action = request.data.get('action', 'approve')
        badge = request.data.get('badge', 'GOLD_COLD_CHAIN')
        notes = request.data.get('admin_notes', 'Inspection passed by Platform Quality Assurance Auditor.')

        if action == 'approve':
            facility.status = 'APPROVED'
            facility.badge = badge
            facility.admin_notes = notes
            facility.inspected_by = request.user
            facility.inspected_at = timezone.now()
            facility.save()
            
            # Recalculate freshness scores for any crops currently linked to this facility
            for produce in facility.stored_produces.all():
                produce.save()
                
            return Response({
                'detail': f'Facility #{facility.id} approved successfully with badge {facility.get_badge_display()}!',
                'facility': StorageFacilitySerializer(facility).data
            })
        elif action == 'reject':
            facility.status = 'REJECTED'
            facility.badge = 'NONE'
            facility.admin_notes = notes
            facility.inspected_by = request.user
            facility.inspected_at = timezone.now()
            facility.save()
            return Response({
                'detail': f'Facility #{facility.id} inspection rejected.',
                'facility': StorageFacilitySerializer(facility).data
            })
        else:
            return Response({'detail': 'Invalid action. Use approve or reject.'}, status=status.HTTP_400_BAD_REQUEST)


class ProduceListView(APIView):
    permission_classes = [permissions.AllowAny]

    def get(self, request):
        produces = Produce.objects.filter(status='AVAILABLE')
        
        farmer_id = request.query_params.get('farmer')
        if farmer_id:
            produces = Produce.objects.filter(farmer_id=farmer_id)
            
        crop_name = request.query_params.get('crop')
        if crop_name:
            produces = produces.filter(name__icontains=crop_name)
            
        sort_by = request.query_params.get('sort')
        if sort_by == 'urgency':
            produces = sorted(produces, key=lambda p: p.freshness_score)
            serializer = ProduceSerializer(produces, many=True)
            return Response(serializer.data)
            
        produces = produces.order_by('-id')
        serializer = ProduceSerializer(produces, many=True)
        return Response(serializer.data)


class ProduceCreateView(APIView):
    def post(self, request):
        if request.user.role != 'FARMER':
            return Response({'detail': 'Only farmers can create listings'}, status=status.HTTP_403_FORBIDDEN)
            
        # Handle file upload for crop harvest picture
        image_file = request.FILES.get('image') or request.data.get('image')
        image_url = ""
        
        # Verify if it's a file upload
        if image_file and hasattr(image_file, 'name'):
            import os
            import uuid
            from django.core.files.storage import default_storage
            from django.core.files.base import ContentFile
            
            # Generate unique filename to avoid conflict
            ext = os.path.splitext(image_file.name)[1]
            filename = f"{uuid.uuid4()}{ext}"
            
            # Save files in the static folder under uploads/
            upload_dir = os.path.join('static', 'uploads')
            if not os.path.exists(upload_dir):
                os.makedirs(upload_dir)
                
            path = default_storage.save(os.path.join(upload_dir, filename), ContentFile(image_file.read()))
            image_url = f"/static/uploads/{filename}"
            
        data = request.data.copy()
        if image_url:
            data['image_url'] = image_url
            
        serializer = ProduceSerializer(data=data)
        if serializer.is_valid():
            serializer.save(farmer=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

