# Generated by Django 5.2.6 on 2026-06-17 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid (Held in Escrow)'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('HELD_IN_ESCROW', 'Held in Escrow'), ('RELEASED', 'Released to Farmer'), ('REFUNDED', 'Refunded to Buyer')], default='UNPAID', max_length=20)),
                ('delivery_type', models.CharField(choices=[('SELF_PICKUP', 'Self Pickup'), ('PLATFORM_DELIVERY', 'Platform Organized Delivery')], default='PLATFORM_DELIVERY', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
